package plantenApp.java.utils;

/**
 * @author bradley
 */
public enum ArrayBindings {

    //TODO VOORANG GEVEN AAN ADVANCED BLADKLEUR, BLOEIKLEUR
    BLADKLEURPERMAAND,
    BLOEIKLEURPERMAAND,
    MAXBLADHOOGTEPERMAAND,
    MINBLOEIHOOGTEPERMAAND,
    MAXBLOEIHOOGTEPERMAAND,
    GRONDSOORT,
    SOCIABILITEIT,
    STRATEGIE,
    HABITUS,
    BLOEIWIJZE,
    LEVENSVORM,
}
