package plantenApp.java.utils;

/**
 * @author bradley
 */
public enum ArrayBindings {
    BLADKLEURPERMAAND,
    BLOEIKLEURPERMAAND,
    MAXBLADHOOGTEPERMAAND,
    MAXBLADHOOGTE,
    MINBLOEIHOOGTEPERMAAND,
    MINGBLOEIHOOGTE,
    MAXBLOEIHOOGTEPERMAAND,
    MAXBLOEIHOOGTE,
    GRONDSOORT,
    SOCIABILITEIT,
    STRATEGIE,
    HABITUS,
    BLOEIWIJZE,
    LEVENSVORM,
}
