package plantenApp.java.utils;


/**
 * @author bradley
 */
public enum Bindings {
    REACTIEANTAGONISTISCHEOMGEVING,
    ONTWIKKELINGSSNELHEID,
    LEVENSDUUR,
    BIJVRIENDELIJK,
    VLINDERVRIENDELIJK,
    EETBAAR,
    KRUIDGEBRUIK,
    GEUREND,
    VORSTGEVOELIG,
    BLADVORM,
    RATIOBLOEIBLAD,
    SPRUITFENOLOGIE,
    BEHANDELING,
    MAAND,
    VOEDINGSBEHOEFTE,
    NECTARWAARDE,
    POLLENWAARDE,
    PERXJAAR,
    BLADKLEUR,
    BLOEIKLEUR,
    BLADHOOGTE,
    BEZONNING,
    VOCHTBEHOEFTE,
    BLADGROOTTE,
    HABITAT,
    STRATEGIE,
    HABITUS,
    BLOEIWIJZE,
    LEVENSVORM,
    TYPE,
    FAMILIE,
    SEARCH
}
