package plantenApp.java.utils;

/**
 * @author bradley
 */
public enum ERequestArrayData {
    BLADKLEURPERMAAND,
    BLOEIKLEURPERMAAND,
    MAXBLADHOOGTEPERMAAND,
    MAXBLADHOOGTE,
    MINBLOEIHOOGTEPERMAAND,
    MINGBLOEIHOOGTE,
    MAXBLOEIHOOGTEPERMAAND,
    MAXBLOEIHOOGTE,
    GRONDSOORT,
    SOCIABILITEIT,
    STRATEGIE,
    HABITUS,
    BLOEIWIJZE,
    LEVENSVORM,
    BIJVRIENDELIJK,
    VLINDERVRIENDELIJK,
    EETBAAR,
    KRUIDGEBRUIK,
    GEUREND,
    VORSTGEVOELIG
}
