package plantenApp.java.utils;

/**
 * @author bradley
 */
@Deprecated
public enum ERequestArrayData {
    BLADKLEURPERMAAND,
    BLOEIKLEURPERMAAND,
    MAXBLADHOOGTEPERMAAND,
    BLADHOOGTE,
    MINBLOEIHOOGTEPERMAAND,
    BLOEIHOOGTE,
    MAXBLOEIHOOGTEPERMAAND,
    GRONDSOORT,
    SOCIABILITEIT,
    STRATEGIE,
    HABITUS,
    BLOEIWIJZE,
    LEVENSVORM,
    BIJVRIENDELIJK,
    VLINDERVRIENDELIJK,
    EETBAAR,
    KRUIDGEBRUIK,
    GEUREND,
    VORSTGEVOELIG
}
